name: Docker Image Build - rdev

on:
  - push

jobs:
  argus_builder:
    uses: chanzuckerberg/github-actions/.github/workflows/argus-docker-build.yaml@v2.13.2
    secrets: inherit
    if: github.actor != 'dependabot[bot]'
    with:
      envs: rdev
      branches_ignore: main,release-please--branches--main
      path_filters: '!.infra/**'
      images: |
        [
          {
            "name": "delta-share",
            "context": ".",
            "dockerfile": "Dockerfile",
            "platform": "linux/amd64"
          }
        ]