project_name: delta-share

builds:
  - binary: delta-share
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-w -s -X github.com/chanzuckerberg/delta-share/version.ReleaseGitSha={{.Commit}} -X github.com/chanzuckerberg/delta-share/version.ReleaseVersion={{.Version}}"
    flags:
      - -trimpath

release:
  github:
    owner: chanzuckerberg
    name: delta-share

brews:
  - description: "The command line tool for the CZI Databricks Delta Share short-lived tokens."
    repository:
      owner: chanzuckerberg
      name: homebrew-tap
    homepage: "https://github.com/chanzuckerberg/delta-share"
    test: system "#{bin}/delta-share version"
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy