name: Create an rdev Stack

on:
  pull_request:
    types: [ labeled, synchronize ]

jobs:
  create-update-stack:
    name: Create/update stack
    runs-on: [ARM64, self-hosted, Linux]
    if: contains(github.event.pull_request.labels.*.name, 'stack')
    permissions:
      id-token: write
      issues: write
      pull-requests: write

    steps:
      - name: Create Stack
        id: create
        uses: chanzuckerberg/argus-artifacts/ci/packages/create-stack@v0.41.0
        with:
          appName: delta-share
          envName: rdev

      - name: Notify
        run: echo "Stack stable at ${{ steps.create.outputs.baseURL }}"