name: Create an Prod Stack

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-stack:
    runs-on: [ARM64, self-hosted, Linux]
    permissions:
      id-token: write
      issues: write
      pull-requests: write

    steps:
      - name: Create Stack in Argus Prod
        id: upsert
        uses: chanzuckerberg/argus-artifacts/ci/packages/create-stack@v0.41.0
        with:
          appName: delta-share
          envName: prod
          waitForDeploymentSeconds: 300

      - name: Notify
        run: echo "Stack stable at ${{ steps.upsert.outputs.baseURL }}"
