name: Docker Image Build - Prod

on:
    workflow_dispatch: {}
    push:

jobs:
  argus_builder:
    uses: chanzuckerberg/github-actions/.github/workflows/argus-docker-build.yaml@v4.0.0
    secrets: inherit
    with:
      envs: prod
      branches_include: 'main'
      path_filters: '!.infra/**'
      images: |
        {
          "backend": {
            "context": "./backend/",
            "dockerfile": "./backend/Dockerfile",
            "platform": "linux/amd64"
          }
        }
