name: Docker Image Build - rdev

on:
  - push

jobs:
  argus_builder:
    uses: chanzuckerberg/github-actions/.github/workflows/argus-docker-build.yaml@v4.0.0
    secrets: inherit
    if: github.actor != 'dependabot[bot]'
    with:
      envs: rdev
      branches_ignore: 'main,release-please--branches--main'
      path_filters: '!.infra/**'
      images: |
        {
          "backend": {
            "context": "./backend/",
            "dockerfile": "./backend/Dockerfile",
            "platform": "linux/amd64"
          }
        }
